### ISSUE TITLE
scheda us: funzione warning errata

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#10]
nella scheda us qualsiasi operazione si faccia ( navigazione tra i record, aggiornamento-inserimento dati)appare la finestra che dice:
il record è stato modificato. Vuoi salvare?

**Comment by slarosa** [comment]
credo sia un problema dovuto a come sono stati memorizzati i valori all'interno della tabella ```us_table``` del database di esempio caricato al primo avvio.

In questo caso viene fatto un check di uguaglianza tra i valori presenti nella scheda US e i valori memorizzati nel DB simile a questo:

```"[u'A']" == "['A']"```
che restituisce ```False``` anche se i valori sono uguali

Una possibile soluzione potrebbe essere quella di aggiornare il DB eliminando la lettera 'u' nei valori dei campi della tabella.

Provo ad aggiornare i campi come segue e dimmi se risolve:
```sql
UPDATE us_table SET inclusi = replace(inclusi, 'u''', '''');
UPDATE us_table SET campioni = replace(campioni, 'u''', '''');
UPDATE us_table SET rapporti = replace(rapporti, 'u''', '''');
UPDATE us_table SET documentazione = replace(documentazione, 'u''', '''');
```
Se gli update sopra risolvono il problema, anche dopo aver aggiunto nuovi valori all'interno del db dalla scheda US, allora possiamo tranquillamente aggiornare il DB di esempio.

**Comment by enzococca** [comment]
Hai ragione, ho aggiornato e ora funziona!

**Comment by slarosa** [comment]
@enzococca cosa succede se si inserisce un nuovo record dalla scheda US? i valori delle liste vengono memorizzate correttamente nel DB?

Comunque, qui d06d17593d67cf136ae210165e27c25fe0434bd1 ho aggiornato il db sqlite.

**Comment by enzococca** [comment]
mi da questo errore

createEditor [delegateComboBox.py:40]
name 'QtGui' is not defined

**Comment by slarosa** [comment]
ancora c'è qualcosa da sistemare nel porting a pyqt5...puoi riprovare con a78cbe1, grazie

**Comment by enzococca** [comment]
adesso non mi compare più l'errore ma non posso salvare. perchè manca il pulsante ok nella finestra di avviso che compare

**Comment by slarosa** [comment]
> adesso non mi compare più l'errore ma non posso salvare. perchè manca il pulsante ok nella finestra di avviso che compare

ok, chiudo questa issue visto che il problema in oggetto è risolto, ci vediamo su #15 e #16 :-)
