### ISSUE TITLE
scheda us: 'NoneType' object has no attribute 'selectedFeatures'

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#13]
nella scheda us -tool-sistemi di controllo-apri scheda us appare l'errore:

on_pushButton_showSelectedFeatures_pressed [pyarchinit_US_mainapp.py:1063]
'NoneType' object has no attribute 'selectedFeatures'

**Comment by pyarchinit** [comment]
Il tasto va testato selezionando geometrie solo da pyarchinit_us_view, che è la view in SL o PG che fonde il layer geometrico pyunitastratigrafiche e us_table.

**Comment by pyarchinit** [comment]
Questo è il procedimento atteso: [Link](https://pyarchinit.github.io/pyarchinit_doc/03_ilplugin.html#apertura-delle-schede-us-da-selezione-su-base-gis)

**Comment by pyarchinit** [comment]
Se la chiamata selectedFeatures non è stata modificata nelle api di Qgis, forse è da segnalare come enhancement (?) per il futuro, dove sarà necessario far apperire un messaggio che segnala la necessità di usare il tasto in coppia con pyarchinit us view.

**Comment by enzococca** [comment]
ho cambiato le classi deprecate in pyarchinit_pyqgis.py e sembra funzionare carica i layer da la scheda sito e le view da la scheda us quando si attiva il gis data viewer

**Comment by slarosa** [comment]
Done in c18b06e46db647cb2eaeb8de1850dfc2b4bf7d54 and a6b259957797bb343517c0d70ab23ea3acd3267c
