### ISSUE TITLE
tasto cancellazione record non funziona

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#15]
in tutte le schede quando si cerca di elimanre un record tramite il tasto cancella record appare la finestra con il worning che permette solo di annullare l'operazione. manca il tasto "ok" per confermare

**Comment by enzococca** [comment]
aHo fatto una prova sulla scheda sito per risolvere il problema: 
nella funzione di cancellazione record ho scritto il codice così:

def on_pushButton_delete_pressed(self):
        msg = QMessageBox.warning(self, "Attenzione!!!",
                                  "Vuoi veramente eliminare il record? \n L'azione è irreversibile", QMessageBox.No|QMessageBox.Yes,
                                  )
        if msg != QMessageBox.Yes:
            QMessageBox.warning(self, "Messaggio!!!", "Azione Annullata!")
Non se è la formula più elegante ma funziona

**Comment by slarosa** [comment]
@enzococca grazie, ho fatto una pulizia qui b97595e8a94d841082429cbafead1be94719e8e7 che dovrebbe risolvere il problema.
