### ISSUE TITLE
Manage paths .qgis2

### ISSUE THREAD

**Issue by serenasensini** [serenasensini/pyarchinit_3#2]
Paths consider .qgis2, they should consider QGIS3

**Comment by slarosa** [comment]
Currently I see only these two line which are refer to old configuration folder 

line 174: https://github.com/serenasensini/pyarchinit_3/blob/qgis3_porting/pyarchinitConfigDialog.py#L174
and line 197: https://github.com/serenasensini/pyarchinit_3/blob/qgis3_porting/pyarchinitConfigDialog.py#L197 

and I'll fix later.
