### ISSUE TITLE
scheda esportazione pdf: non esporta

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#25]
'US' object does not support indexing
__init__ [pyarchinit_exp_Periodosheet_pdf.py:109]

da notare che l'esportazione in pdf dalla scheda us funziona

**Comment by slarosa** [comment]
l'ultima master dovrebbe risolvere parzialmente il problema.

**Comment by enzococca** [comment]
'US' object does not support indexing
on_pushButton_exp_pdf_pressed [pyarchinit_pdf_export_mainapp.py:159]

**Comment by enzococca** [comment]
'TAFONOMIA' object has no attribute 'area'
generate_list_US_pdf [pyarchinit_pdf_export_mainapp.py:291]

**Comment by slarosa** [comment]
mmm...sulla 2 funzionava?

**Comment by enzococca** [comment]
La scheda us la esporta ma non la lista us. Mancano le altre schede. Quando
provo cmq a esportare le schede us mi compaiono una serie di finistre dove
dentro ci sono scritti i dati da esportare

Il Ven 13 Apr 2018, 22:01 Salvatore Larosa <notifications@github.com> ha
scritto:

**Comment by enzococca** [comment]
Cmq credo che nella versione 2 funzionava

Il Ven 13 Apr 2018, 22:01 Salvatore Larosa <notifications@github.com> ha
scritto:
