### ISSUE TITLE
scheda tafonomia : errore esportazione singole schede pdf

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#32]
eval() arg 1 must be a string, bytes or code object

create_sheet [pyarchinit_exp_Tafonomiasheet_pdf.py:539]

**Comment by slarosa** [comment]
@enzococca dall'errore credo tu stia provando una vecchia versione del plugin. Hai provato l'ultima master? quell'errore dovrebbe essere già stato risolto qui 90fe50a7b794fe2abb9c9af61bb0e04befe5d045
