### ISSUE TITLE
scheda us : creazione codice periodo error

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#36]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\users\\luca\\testcodper.txt' 

 File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\modules\db\pyarchinit_db_manager.py", line 1027, in update_cont_per
    f = open('C:\\users\\luca\\testcodper.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\users\\luca\\testcodper.txt'

da commentare??

**Comment by enzococca** [comment]
anche se si commenta l'errore non si visualizza ma non crea i codici periodo

**Comment by slarosa** [comment]
Forse correlato a #35, il quale è stato risolto nella master

**Comment by enzococca** [comment]
il codice periodo nella scheda periodizzazione viene salvato., ma nella scheda us quando si prova a creare il codice periodo da questo errore:
TypeError: 'int' object is not subscriptable
File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\modules\db\pyarchinit_utility.py", line 177, in deunicode_list
    elif self.list[i][0:3] == '"""':
TypeError: 'int' object is not subscriptable

**Comment by slarosa** [comment]
inserendo un nuovo record o scorrendo i record?
Ho fatto entrambe le prove e non ho errori.

**Comment by enzococca** [comment]
hai creato il codice periodo dalla scheda us?

**Comment by enzococca** [comment]
quando provi a creare il codice periodo da qui mi esce quell'errore

![capture](https://user-images.githubusercontent.com/3473064/38801208-8a2a4472-4169-11e8-9660-69af119c0e5f.JPG)

**Comment by enzococca** [comment]
ottimo!!
