### ISSUE TITLE
scheda sito db sqlite: 2 layer non caricati

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#42]
dalla scheda sito - tool- carica i layer per il disegno:
layer doc viw e pyarchinit us_negative esce layr noon validi

@pyarchinit quanti e quali layar dovrebbe caricare?

**Comment by pyarchinit** [comment]
Confermato anche in Posgtres.
SI tratta dei due layer per la doc delle sezioni e prospetti aggiunti da SImone Berto. Tutto il sistema va rivisto perchè presenta delle carenze di procedura. I layer che non carica sono
pyarchinit_us_negative_doc e pyarchinit_us_negative_doc_view (non presente nello schema di DB di PG).

Suggerisco di togliere commentandole le righe che mandano l'errore.
