### ISSUE TITLE
scheda sito caricamento layer doppioni

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#43]
dalla scheda sito - tool- carica i layer per questo sito
si verifica, sia per sqlite che posgres, che carica layer doppi e compaiono dei worning per 4 layer non validi

**Comment by slarosa** [comment]
Questi sono i layer non validi:
* Resgistro documentazione
* Documentazione Vista
* US Negative per sezioni/elevati

**Comment by pyarchinit** [comment]
Il pulsante deve ritornare i seguenti layer indipendentemente che via siano dati o meno.
l'importante è che eseguano la query sul campo corretto.

il campo è stato aggiunto accanto al nome per  aiutare nello sviluppo del corretto funzionamento.


![immagine](https://user-images.githubusercontent.com/1929829/38894518-bc23eec2-428d-11e8-80f6-ea5c24a8bd98.png)

**Comment by pyarchinit** [comment]
i 4 layer che non carica devono essere totalmente rivisti in futuro con tutto il sistema di documentazione. non è possibile affrontarli allo stato attuale della progettazione.
