### ISSUE TITLE
Scheda Sito: pulsante caricamento layer postgis vs sqlite: comportamento  non uguale

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#44]
quando si caricano i layer da sqlite db i file vengono carcati simultaneamnte senza chiedere il sistema di riferimento. per postgres per ognio layer si chiede il sistema di riferimento

**Comment by pyarchinit** [comment]
Domanda (perchè non ne ho idea): dipende da QGIS, python, dal nostro codice oppure dalle impostazioni particolari di QGIS sulla tua macchina?

**Comment by enzococca** [comment]
@pyarchinit  credo dipenda dal codice perché nella ciamata al db postgres è settato la funzione per le chiamte al srs

**Comment by slarosa** [comment]
Quale pulsante, il primo o il secondo?

**Comment by enzococca** [comment]
entrambi

**Comment by enzococca** [comment]
ma vale per postgres

**Comment by enzococca** [comment]
Non ho capito se questo comportamento in postgres abbiamo deciso di lasciarlo così ma continua a chiedere sempre il sistema di riferimento per ogni layer quando si carica
