### ISSUE TITLE
Scheda US: Eliminare nel toggle button gis data visualizer il caricamento stile da postgres

### ISSUE THREAD

**Issue by pyarchinit** [serenasensini/pyarchinit_3#47]
Eliminare nel toggle button gis data visualizer la possibilità di caricare il file di stile da applicare alla view.

**Comment by pyarchinit** [comment]
Si è verificato un errore durante l'esecuzione del codice Python: 

TypeError: QgsVectorLayer.loadNamedStyle(): arguments did not match any overloaded call:   overload 1: argument 1 has unexpected type 'tuple'   overload 2: argument 1 has unexpected type 'tuple' 
Traceback (most recent call last):
  File "C:/Users/Windows/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\pyarchinit_US_mainapp.py", line 1998, in on_pushButton_search_go_pressed
    self.pyQGIS.charge_vector_layers(self.DATA_LIST)
  File "C:/Users/Windows/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\modules\gis\pyarchinit_pyqgis.py", line 682, in charge_vector_layers
    layerUS.loadNamedStyle(style_path)
TypeError: QgsVectorLayer.loadNamedStyle(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'tuple'
  overload 2: argument 1 has unexpected type 'tuple'

**Comment by enzococca** [comment]
questo succede con  postgres? in sqlite non chiede lo stile. Inoltre compare un finestra che dice layer non valido ma carica i due layer che dove caricare quote_us_view e pyarchini_us_view

**Comment by pyarchinit** [comment]
Si, era stata aggiunto questa funzione solo per postgres ma è melgio togliere la scelta dello stile. meglio che carichi quello di default di qgis. questo a me blocca il caricamento dei layer pyarchinit-us-view e pyarhcinit-quote-view.
