### ISSUE TITLE
scheda us: errore sul pulsante apri scheda selezionata

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#49]
db sqlite: in scheda us  - tool- funzioni di controllo
se azione il pulsante **apri scheda selezionata** compare l'errore:

AttributeError: 'NoneType' object has no attribute 'selectedFeatures' 

File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\pyarchinit_US_mainapp.py", line 1064, in on_pushButton_showSelectedFeatures_pressed
    features_list = self.iface.mapCanvas().currentLayer().selectedFeatures()
AttributeError: 'NoneType' object has no attribute 'selectedFeatures'

**Comment by pyarchinit** [comment]
Ricordarsi che funziona solo se si selezionano le US da pyarchinit_us_view
