### ISSUE TITLE
scheda lapidei cannot import name 'mode'

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#5]
File "/home/enzo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit_3-master/pyarchinit_Inv_Lapidei.py", line 30, in 
    from sqlalchemy.sql.functions import mode
ImportError: cannot import name 'mode'

**Comment by slarosa** [comment]
quale versione di sqlalchemy?

**Comment by enzococca** [comment]
1.0.11

**Comment by slarosa** [comment]
La funzione ```mode``` è stata inserita nella versione 1.1. Ma guardando il codice sembra essere inutilizzata, @pyarchinit puoi confermare?

**Comment by enzococca** [comment]
Confermo io è inutilizzato
