### ISSUE TITLE
scheda us: errore esportazioni tavole

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#50]
nella scheda us - tool- esportazione
avviando la funzione esportazione tavole esce l'errore:
NameError: name 'QgsCoordinateReferenceSystem' is not defined

 File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\modules\utility\pyarchinit_print_utility.py", line 344, in charge_layer_sqlite
    srs = QgsCoordinateReferenceSystem(3004, QgsCoordinateReferenceSystem.PostgisCrsId)
NameError: name 'QgsCoordinateReferenceSystem' is not defined

**Comment by pyarchinit** [comment]
Sistema sperimentale mai sviluppato fino in fondo.

Visto il potenziamento del compositore di stampe si potrebbe pensare anche di eliminarlo. 

Funzionava grazie ad un massiccio copia e incolla da un altro plugin e NON SCALAVA I DISEGNI PER FORMATI FOGLIO CONVENZIONALI , ma adattava il foglio ad una scala prefissata, tipo 1:20. Questo porta ad avere dei perfetti overlayer all'inglese, ma non stampabili. va aggiunto che pescava i crocicchi e una pianta generale da shape realizzati al volo durante lo sviluppo. Da rivedere e valutare se tenere.

**Comment by slarosa** [comment]
Se il layout non è complesso ci provo...

**Comment by slarosa** [comment]
implementato in 7fa0953903f0b73e2ca6cd3d7f9c21d8d9bce74c. da verificare.
