### ISSUE TITLE
Scheda US - ordine stratigrafico non salva più i dati nel database (sia spatialite che postgtres)

### ISSUE THREAD

**Issue by pyarchinit** [serenasensini/pyarchinit_3#51]
Scheda us, tools, pulsante Ordine stratigrafico.

il processo gira e termina senza mandare errori.

il processo salva temporaneamente in un dizionario (o una lista) una serie di numeri, che vengono infine salvati con un update nelle singole schede di us_table nel campo order_layer.

il sistema sembra girare correttamente ma a fine processo in tabella, dopo essere stati cancellati tutti i dati nel campo order_layer, non vengono salvati i nuovi numeri.

**Comment by enzococca** [comment]
@slarosa le funzioni per l'order_layer le trovi in pyarchinit_pyqgis sotto la classe Order_layer_v2

**Comment by slarosa** [comment]
Si, ho visto, ma non vedo nulla di anomalo

**Comment by slarosa** [comment]
Da chiudere?

**Comment by slarosa** [comment]
Chiuso, @pyarchinit se riscontri il problema riaprilo!
