### ISSUE TITLE
scheda sito e scheda us: non salva

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#9]
Quando si inseriscono nuovi dati e si prova a salvare appare una finestra che dice:
Attenzione 2!
name 'func' is not defined

**Comment by enzococca** [comment]
Credo valga per tutte le schede

**Comment by slarosa** [comment]
Gradito anche qui un test con le nuove modifiche.

**Comment by enzococca** [comment]
Continua a darmi lo stesso errore

**Comment by slarosa** [comment]
Avevo dimenticato un import, nella nuova modifica dovrebbe funzionare.

**Comment by enzococca** [comment]
creso che l'errore sia dovuto nella funzione max_num_id richiamato da tutte le schede nel file pyarchinit_db_manager.py alla riga 894
exec_str = "session.query(**func**.max({}.{}))".format(self.table_class, self.field_id)

**Comment by enzococca** [comment]
Ok ora salva!!
